version: "3"
services:
  development:
    build:
      context: .
      target: development-build
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 7000:7000
    stdin_open: true
    tty: true

  production:
    build:
      context: .
      target: production-nginx
    ports:
      - 80:80
